IPSSaludYVida/urls.py
from django.contrib import admin
from django.urls import path
from clinica.views import IndexView, Pacientes,ServicioPaciente
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),

    path('Pacientes/', Pacientes.as_view(), name='Paciente'),

    path('ServicioPaciente/', ServicioPaciente.as_view(), name='ServicioPaciente'),


    path('', include('clinica.urls')),
]

clinica/urls.py
from operator import index

from django.conf.urls.i18n import urlpatterns
from django.urls import path, include
from.views import *

urlpatterns = [

    path('pacientes', ListaPacientes.as_view(), name='pacientes'),
    #path('', views.index, name='index'),
    path('servicios', ListaServicios.as_view(), name='servicios'),

    path('crear_servicio/', crear_servicio, name='crear_servicio'),

    path('crear_triage/', crear_triage, name='crear_triage'),

    path('eliminar_servicio/<int:id_servicio>/', eliminar_servicio, name='eliminar_servicio'),

    path('editar_servicio/<int:id_servicio>/', editar_servicio, name='editar_servicio'),

    path('crear_paciente/', crear_usuario, name='crear_paciente'),

    path('crear_donacion/', crear_donacion, name='crear_donacion'),

    path('crear_voluntad/', crear_voluntad, name='crear_voluntad'),

    path('', IndexView.as_view(), name='index'),

]

clinica/forms.py
from django import forms
from django.db.models import Model

from .models import Usuario, Servicio, Triage, OpocisionDonacion, VoluntaAnticipada, Discapacidades, PrestadoresSalud
from datetime import datetime
#from django.forms import


class ServicioForm2(forms.ModelForm):

    triage = forms.ModelChoiceField(
        queryset=Triage.objects.all(),
        widget=forms.Select,
        required=True
    )

    class Meta:
        model = Servicio
        fields = [
            'usuario', 'prestador_salud', 'fecha_atencion', 'hora_atencion',
            'modalidad_servicio', 'grupo_servicio', 'via_ingreso', 'entorno_atencion',
            'causa_atencion', 'triage', 'diagnostico', 't_diagnostico'
        ]

        widgets = {
            'fecha_atencion': forms.DateInput(attrs={'type': 'date'}),
            'hora_atencion': forms.TimeInput(attrs={'type': 'time'}),
        }


class UsuarioForm(forms.ModelForm):

    donacion = forms.ModelChoiceField(
        queryset=OpocisionDonacion.objects.all(),
        widget=forms.Select,
        required=True
    )

    voluntad = forms.ModelChoiceField(
        queryset=VoluntaAnticipada.objects.all(),
        widget=forms.Select,
        required=True
    )


    class Meta:
        model = Usuario
        fields = [
            'tipo_documento', 'numero_documento', 'primer_nombre', 'segundo_nombre',
            'primer_apellido', 'segundo_apellido', 'sexo_biologico', 'ident_genero',
            'ocupacion', 'discapacidad', 'donacion', 'voluntad', 'nacionalidad',
            'pais_residencia', 'departamento_municipio', 'comunidad_etnia', 'etnia',
            'zona_residencia', 'entidad', 'fecha_nacimiento', 'hora_nacimiento',
        ]

        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
            'hora_nacimiento': forms.TimeInput(attrs={'type': 'time'}),
            'discapacidad': forms.SelectMultiple(attrs={'type': 'text'}),
            'nacionalidad': forms.SelectMultiple(attrs={'type': 'text'}),
        }

templates/servicios/edicion_servicio.html
{% extends 'layouts/layoutPrincipal.html' %}
{% block content %}
    {% load widget_tweaks %}
    <!--**********************FORMULARIO PARA LA EDICION DE SERVICIOS***********************-->
<h2 class="title-servicio">Editar Servicio</h2>
    <div class="form-servicios">
<form method="post">
    {% csrf_token %}
    <div class="content-formServicios">
        <div class="content-form">
           {{ form.usuario.label }} {{ form.usuario|add_class:"select-form" }}
            {{ form.prestador_salud.label }} {{ form.prestador_salud|add_class:"select-form" }}
            {{ form.fecha_atencion.label }} {{ form.fecha_atencion|add_class:"select-form" }}
            {{ form.hora_atencion.label }} {{ form.hora_atencion|add_class:"select-form" }}
            {{ form.modalidad_servicio.label }} {{ form.modalidad_servicio|add_class:"select-form" }}
            {{ form.grupo_servicio.label }} {{ form.grupo_servicio|add_class:"select-form" }}
        </div>
        <div class="content-form">
        {{ form.via_ingreso.label }} {{ form.via_ingreso|add_class:"select-form" }}
        {{ form.entorno_atencion.label }} {{ form.entorno_atencion|add_class:"select-form" }}
        {{ form.causa_atencion.label }} {{ form.causa_atencion|add_class:"select-form" }}
        {{ form.diagnostico.label }} {{ form.diagnostico|add_class:"select-form" }}
            {{ form.t_diagnostico.label }} {{ form.t_diagnostico|add_class:"select-form" }}
            <label for="id_triage">Añadir Triage:</label>
                {{ form.triage|add_class:"select-form" }}
            <button type="button" class="button-triage" data-bs-toggle="modal" data-bs-target="#addTriageModal">
                + Añadir Triage
            </button>
        </div>


    </div>
            <div class="button-container">
            <button type="submit" class="button-submit">Guardar Servicio</button>
        </div>
</form>
    </div>
    
        <script>
function submitTriageForm() {
    // Obtiene los datos del formulario del Triage
    const formData = new FormData(document.getElementById('triageForm'));

    // Realiza la solicitud AJAX para enviar el formulario
    fetch("{% url 'crear_triage' %}", {
        method: "POST",
        headers: {
            "X-CSRFToken": formData.get('csrfmiddlewaretoken')
        },
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Añade el nuevo Triage al campo de selección
            const triageSelect = document.getElementById("id_triage");
            const newOption = new Option(data.clasificacion, data.id, false, true);
            triageSelect.add(newOption);

        } else {
            alert("Error al guardar el triage");
        }
    })
    .catch(error => console.error("Error:", error));
    
}

</script>
{% endblock %}

templates/servicios/formulario_servicio.html
{% extends 'layouts/layoutPrincipal.html' %}
{% block content %}
    {% load widget_tweaks %}
    <!--**********************FORMULARIO PARA LA CREACION DE SERVICIOS***********************-->
<h2 class="title-servicio">Crear Nuevo Servicio</h2>
    <div class="form-servicios">
<form method="post">
    {% csrf_token %}
    <div class="content-formServicios">
        <div class="content-form">
           {{ form.usuario.label }} {{ form.usuario|add_class:"select-form" }}
            {{ form.prestador_salud.label }} {{ form.prestador_salud|add_class:"select-form" }}
            {{ form.fecha_atencion.label }} {{ form.fecha_atencion|add_class:"select-form" }}
            {{ form.hora_atencion.label }} {{ form.hora_atencion|add_class:"select-form" }}
            {{ form.modalidad_servicio.label }} {{ form.modalidad_servicio|add_class:"select-form" }}
            {{ form.grupo_servicio.label }} {{ form.grupo_servicio|add_class:"select-form" }}
        </div>
        <div class="content-form">
        {{ form.via_ingreso.label }} {{ form.via_ingreso|add_class:"select-form" }}
        {{ form.entorno_atencion.label }} {{ form.entorno_atencion|add_class:"select-form" }}
        {{ form.causa_atencion.label }} {{ form.causa_atencion|add_class:"select-form" }}
        {{ form.diagnostico.label }} {{ form.diagnostico|add_class:"select-form" }}
            {{ form.t_diagnostico.label }} {{ form.t_diagnostico|add_class:"select-form" }}
            <label for="id_triage">Añadir Triage:</label>
                {{ form.triage|add_class:"select-form" }}
            <button type="button" class="button-triage" data-bs-toggle="modal" data-bs-target="#addTriageModal">
                + Añadir Triage
            </button>
        </div>


    </div>
            <div class="button-container">
            <button type="submit" class="button-submit">Guardar Servicio</button>
        </div>
</form>
    </div>

    <!--************************VENTANA MODAL***************-->
    <div class="modal fade" id="addTriageModal" tabindex="-1" aria-labelledby="addTriageModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addTriageModalLabel">Añadir Nuevo Triage</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="triageForm">
                    {% csrf_token %}
                    <label for="fechaTriage">Fecha Triage:</label>
                    <input type="date" name="fechaTriage" class="form-control" required>
                    <label for="horaTriage">Hora Triage:</label>
                    <input type="time" name="horaTriage" class="form-control" required>
                    <label for="ClasificacionTriage">Clasificación Triage:</label>
                    <select name="ClasificacionTriage" class="form-control">
                        <option value="01">TRIAGE I</option>
                        <option value="02">TRIAGE II</option>
                        <option value="03">TRIAGE III</option>
                        <option value="04">TRIAGE IV</option>
                        <option value="05">TRIAGE V</option>
                    </select>
                    <button type="button" class="button-content mt-2" onclick="submitTriageForm()">Guardar Triage</button>
                </form>
            </div>
        </div>
    </div>
    </div>
    <!--*************************************************************************-->
    
    <script>
function submitTriageForm() {
    // Obtiene los datos del formulario del Triage
    const formData = new FormData(document.getElementById('triageForm'));

    // Realiza la solicitud AJAX para enviar el formulario
    fetch("{% url 'crear_triage' %}", {
        method: "POST",
        headers: {
            "X-CSRFToken": formData.get('csrfmiddlewaretoken')
        },
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Añade el nuevo Triage al campo de selección
            const triageSelect = document.getElementById("id_triage");
            const newOption = new Option(data.clasificacion, data.id, false, true);
            triageSelect.add(newOption);

        } else {
            alert("Error al guardar el triage");
        }
    })
    .catch(error => console.error("Error:", error));
    
}
</script>
{% endblock %}

templates/servicios/servicios.html
{% extends 'layouts/layoutPrincipal.html' %}
{% load static %}
{% block content %}

    <div class="tablePage">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <a href="{% url 'crear_servicio' %} " class="text-decoration-none text-black">
        <div class="add-button">
            <button class="button-content">
                <p>Agregar</p>
            </button>
        </div>
    </a>
        {% if servicios %}
        <table class="tableData">
            <tr>
                <th scope="col">Prestador Salud</th>
                <th scope="col">Usuario</th>
                <th scope="col">Fecha atencion</th>
                <th scope="col">Hora atencion</th>
                <th scope="col">Modalidad servicio</th>
                <th scope="col">Grupo servicio</th>
                <th scope="col">Diagnostico</th>
                <th scope="col">Entorno atencion</th>
                <th scope="col">Triage</th>
                <th scope="col">Causa Atencion</th>
                <th scope="col">Acciones</th>
            </tr>
            {% for servicio in servicios %}
            <tr>
                <td id="{{ servicio.uuid }}" scope="row">{{ servicio.prestador_salud }}</td>
                <td>{{ servicio.usuario }}</td>
                <td>{{ servicio.fecha_atencion }}</td>
                <td>{{ servicio.hora_atencion }}</td>
                <td>{{ servicio.get_modalidad_servicio_display }}</td>
                <td>{{ servicio.get_grupo_servicio_display }}</td>
                <td>{{ servicio.diagnostico }}</td>
                <td>{{ servicio.get_entorno_atencion_display }}</td>
                <td>{{ servicio.triage }}</td>
                <td>{{ servicio.causa_atencion }}</td>
                <td>
                    <div class="button-group">
                        <button class="edit-button" onclick="location.href='{% url 'editar_servicio' servicio.idServicioSalud %}'">
                         <ion-icon name="create-outline" class="icon-table"></ion-icon>
                        </button>
                         <button class="eliminate-button" onclick="confirmarEliminacion({{ servicio.idServicioSalud }})">
                            <ion-icon name="trash-outline" class="icon-table"></ion-icon>
                        </button>
                    </div>
                </td>
                {% endfor %}
            </tr>
        </table>
        {% else %}
            <h1>No hay datos de los Servicios</h1>
        {% endif %}
    </div>

    <script>
function confirmarEliminacion(id) {
    if (confirm("¿Estás seguro de que deseas eliminar este servicio?")) {
        fetch(`/eliminar_servicio/${id}/`, {
            method: "POST",
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Recargar la página o eliminar la fila de la tabla
                location.reload(); // O puedes eliminar la fila directamente si lo prefieres
            } else {
                alert("Error al eliminar el servicio");
            }
        })
        .catch(error => console.error("Error:", error));
    }
}
</script>
{% endblock %}