IPSSaludYVida/urls.py
from django.contrib import admin
from django.urls import path
from clinica.views import IndexView, Pacientes,ServicioPaciente
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),

    path('Pacientes/', Pacientes.as_view(), name='Paciente'),

    path('ServicioPaciente/', ServicioPaciente.as_view(), name='ServicioPaciente'),


    path('', include('clinica.urls')),
]

clinica/urls.py
from operator import index

from django.conf.urls.i18n import urlpatterns
from django.urls import path, include
from.views import *

urlpatterns = [

    path('pacientes', ListaPacientes.as_view(), name='pacientes'),
    #path('', views.index, name='index'),
    path('servicios', ListaServicios.as_view(), name='servicios'),

    path('crear_servicio/', crear_servicio, name='crear_servicio'),

    path('crear_triage/', crear_triage, name='crear_triage'),

    path('eliminar_servicio/<int:id_servicio>/', eliminar_servicio, name='eliminar_servicio'),

    path('editar_servicio/<int:id_servicio>/', editar_servicio, name='editar_servicio'),

    path('crear_paciente/', crear_usuario, name='crear_paciente'),

    path('crear_donacion/', crear_donacion, name='crear_donacion'),

    path('crear_voluntad/', crear_voluntad, name='crear_voluntad'),

    path('', IndexView.as_view(), name='index'),

]

clinica/forms.py
from django import forms
from django.db.models import Model

from .models import Usuario, Servicio, Triage, OpocisionDonacion, VoluntaAnticipada, Discapacidades, PrestadoresSalud
from datetime import datetime
#from django.forms import


class ServicioForm2(forms.ModelForm):

    triage = forms.ModelChoiceField(
        queryset=Triage.objects.all(),
        widget=forms.Select,
        required=True
    )

    class Meta:
        model = Servicio
        fields = [
            'usuario', 'prestador_salud', 'fecha_atencion', 'hora_atencion',
            'modalidad_servicio', 'grupo_servicio', 'via_ingreso', 'entorno_atencion',
            'causa_atencion', 'triage', 'diagnostico', 't_diagnostico'
        ]

        widgets = {
            'fecha_atencion': forms.DateInput(attrs={'type': 'date'}),
            'hora_atencion': forms.TimeInput(attrs={'type': 'time'}),
        }


class UsuarioForm(forms.ModelForm):

    donacion = forms.ModelChoiceField(
        queryset=OpocisionDonacion.objects.all(),
        widget=forms.Select,
        required=True
    )

    voluntad = forms.ModelChoiceField(
        queryset=VoluntaAnticipada.objects.all(),
        widget=forms.Select,
        required=True
    )


    class Meta:
        model = Usuario
        fields = [
            'tipo_documento', 'numero_documento', 'primer_nombre', 'segundo_nombre',
            'primer_apellido', 'segundo_apellido', 'sexo_biologico', 'ident_genero',
            'ocupacion', 'discapacidad', 'donacion', 'voluntad', 'nacionalidad',
            'pais_residencia', 'departamento_municipio', 'comunidad_etnia', 'etnia',
            'zona_residencia', 'entidad', 'fecha_nacimiento', 'hora_nacimiento',
        ]

        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
            'hora_nacimiento': forms.TimeInput(attrs={'type': 'time'}),
            'discapacidad': forms.SelectMultiple(attrs={'type': 'text'}),
            'nacionalidad': forms.SelectMultiple(attrs={'type': 'text'}),
        }

templates/pacientes/formulario_paciente.html
{% extends 'layouts/layoutPrincipal.html' %}
{% block content %}
    {% load widget_tweaks %}
    <!--**********************FORMULARIO PARA LA CREACION DE SERVICIOS***********************-->
         <h2>Crear Nuevo Paciente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.primer_nombre.label }} {{ form.primer_nombre }}
        {{ form.segundo_nombre.label }} {{ form.segundo_nombre }}
        {{ form.primer_apellido.label }} {{ form.primer_apellido }}
        {{ form.segundo_apellido.label }} {{ form.segundo_apellido }}
        {{ form.fecha_nacimiento.label }} {{ form.fecha_nacimiento }}
        {{ form.hora_nacimiento.label }} {{ form.hora_nacimiento }}
        {{ form.sexo_biologico.label }} {{ form.sexo_biologico }}
        {{ form.ident_genero.label }} {{ form.ident_genero }}
        {{ form.ocupacion.label }} {{ form.ocupacion }}
        {{ form.discapacidad.label }} {{ form.discapacidad }}
        {{ form.nacionalidad.label }} {{ form.nacionalidad }}
        {{ form.pais_residencia.label }} {{ form.pais_residencia }}
        {{ form.departamento_municipio.label }} {{ form.departamento_municipio }}
        {{ form.comunidad_etnia.label }} {{ form.comunidad_etnia }}
        {{ form.etnia.label }} {{ form.etnia }}
        {{ form.zona_residencia.label }} {{ form.zona_residencia }}
        {{ form.entidad.label }} {{ form.entidad }}

        <label for="id_donacion">Oposicion Donacion:</label>
                {{ form.donacion }}
        <button type="button" class="button-triage" data-bs-toggle="modal" data-bs-target="#addDonacionModal">
                + Añadir Donacion
        </button>

        <button type="submit">Crear Usuario</button>
    </form>

    <!--******************VENTANA MODAL DONACION**********************-->
    <div class="modal fade" id="addDonacionModal" tabindex="-1" aria-labelledby="addDonacionModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addDonacionModalLabel">Añadir Nueva Donacion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
            </div>
            <div class="modal-body">
                <form id="DonacionForm">
                    {% csrf_token %}
                    <label for="fechaDonacion">Fecha Donacion:</label>
                    <input type="date" name="fechaDonacion" class="form-control" required>
                    <label for="manifestacionOpo">Manifestacion Donacion:</label>
                    <select name="manifestacionOpo" class="form-control">
                        <option value="01">Si</option>
                        <option value="02">No</option>
                    </select>
                    <button type="button" class="button-content mt-2" onclick="submitDonacionForm()">Guardar Donacion</button>
                </form>
            </div>
        </div>
    </div>
    </div>
    <!--******************************************************************************************-->
    <script>

function submitDonacionForm() {
    // Obtiene los datos del formulario del Triage
    const formData = new FormData(document.getElementById('DonacionForm'));

    // Realiza la solicitud AJAX para enviar el formulario
    fetch("{% url 'crear_donacion' %}", {
        method: "POST",
        headers: {
            "X-CSRFToken": formData.get('csrfmiddlewaretoken')
        },
        body: formData
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            // Añade el nuevo Triage al campo de selección
            const OposicionDonacionSelect = document.getElementById("id_donacion");
            const newOption = new Option(data.manifestacion, data.id, false, true);
            OposicionDonacionSelect.add(newOption);

        } else {
            alert("Error al guardar la donacion");
        }
    })
    .catch(error => console.error("Error:", error));

}
    </script>
{% endblock %}

templates/pacientes/pacientes.html
{% extends 'layouts/layoutPrincipal.html' %}
{% load static %}
{% block content %}

    <div class="tablePage">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <a href="{% url 'crear_paciente' %} " class="text-decoration-none text-black">
        <div class="add-button">
            <button class="button-content">
                <p>Agregar</p>
            </button>
        </div>
    </a>
        {% if pacientes %}
        <table class="tableData">
            <tr>
                <th scope="col">Primer Nombre</th>
                <th scope="col">Segundo Nombre</th>
                <th scope="col">Primer Apellido</th>
                <th scope="col">Segundo Apellido</th>
                <th scope="col">Tipo Documento</th>
                <th scope="col">Numero Documento</th>
                <th scope="col">EPS</th>
                <th scope="col">Discapacidades</th>
                <th scope="col">Acciones</th>
            </tr>
            {% for paciente in pacientes %}
            <tr>
                <td id="{{ paciente.uuid }}" scope="row">{{ paciente.primer_nombre }}</td>
                <td>{{ paciente.segundo_nombre }}</td>
                <td>{{ paciente.primer_apellido }}</td>
                <td>{{ paciente.segundo_apellido }}</td>
                <td>{{ paciente.tipo_documento }}</td>
                <td>{{ paciente.numero_documento }}</td>
                <td>{{ paciente.entidad }}</td>
                <td>    {% for disc in paciente.discapacidad.all %}
                            {{ disc.calDiscapacidad }}{% if not forloop.last %}, {% endif %}
                        {% empty %}
                            Sin discapacidades
                        {% endfor %}
                </td>
                <td>
                    <div class="button-group">
                        
                         <button class="eliminate-button" onclick="confirmarEliminacion({{ usuario.idUsuario }})">
                            <ion-icon name="trash-outline" class="icon-table"></ion-icon>
                        </button>
                    </div>
                </td>
                {% endfor %}
            </tr>
        </table>
        {% else %}
            <h1>No hay datos de los pacientes</h1>
        {% endif %}
    </div>
    <script>
function confirmarEliminacion(id) {
    if (confirm("¿Estás seguro de que deseas eliminar este paciente?")) {
        fetch(`/eliminar_servicio/${id}/`, {
            method: "POST",
            headers: {
                "X-CSRFToken": "{{ csrf_token }}"
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Recargar la página o eliminar la fila de la tabla
                location.reload(); // O puedes eliminar la fila directamente si lo prefieres
            } else {
                alert("Error al eliminar el servicio");
            }
        })
        .catch(error => console.error("Error:", error));
    }
}
</script>
{% endblock %}